title: Jekyll-Store
description: CMS-Free Ecommerce Solution
baseurl: '/jekystore.github.io'
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - CNAME
